return function(colors)
	return {

		-- Default highlight groups

		Comment = { fg = colors.overlay0 },

		Constant = { fg = colors.teal, style = { "bold" } },
		String = { fg = colors.green },
		Character = { fg = colors.peach },
		Number = { fg = colors.blue },
		Boolean = { fg = colors.peach, style = { "bold" } },
		Float = { link = "Number" },

		Identifier = { fg = colors.text },
		Function = { fg = colors.sapphire, style = { "bold" } },

		Statement = { fg = colors.red, style = { "bold" } },
		Conditional = { link = "Statement" },
		Repeat = { link = "Statement" },
		Label = { link = "Statement" },
		Operator = { fg = colors.blue },
		Keyword = { link = "Statement" },
		Exception = { link = "Statement" },

		PreProc = { fg = colors.peach },
		Include = { link = "PreProc" },
		Define = { link = "PreProc" },
		Macro = { link = "PreProc" },
		PreCondit = { link = "PreProc" },

		Type = { fg = colors.yellow, style = { "bold" } },
		StorageClass = { link = "Type" },
		Structure = { link = "Type" },
		Typedef = { link = "Type" },

		Special = { fg = colors.peach },
		SpecialChar = { fg = colors.peach },
		Tag = { fg = colors.red },
		Delimiter = { fg = colors.peach },
		SpecialComment = { fg = colors.yellow },
		Debug = { fg = colors.mauve },

		Underlined = { style = { "underline" } },
		Bold = { style = { "bold" } },
		Italic = { style = { "italic" } },

		Ignore = { fg = colors.overlay0 },
		Error = { fg = colors.red },
		Todo = { fg = colors.yellow },

		Added = { fg = colors.green },
		Changed = { fg = colors.peach },
		Removed = { fg = colors.red },

		-- Special groups

		CursorLineNr = { fg = colors.text },
		LineNr = { fg = colors.sky },
		FloatBorder = { fg = colors.blue },
		Folded = { fg = colors.crust, bg = "#45475a" },
		StatusLineNC = { fg = colors.text },
		VertSplit = { fg = colors.blue },
		WinSeparator = { link = "VertSplit" },

		BufferLineOffsetSeparator = { fg = colors.red },
		NeoTreeVertSplit = { fg = colors.red },
		NeoTreeWinSeparator = { link = "NeoTreeVertSplit" },

		DapBreakpointSymbol = { fg = colors.red },
		DapStoppedSymbol = { link = "DapBreakpointSymbol" },

		-- Custom colors

		Builtin = { fg = colors.blue },

		-- Tree sitter highlight groups

		TSComment = { link = "Comment" },

		TSConstant = { link = "Constant" },
		TSString = { link = "String" },
		TSCharacter = { link = "Character" },
		TSNumber = { link = "Number" },
		TSBoolean = { link = "Boolean" },
		TSFloat = { link = "Float" },

		TSConditional = { link = "Conditional" },
		TSRepeat = { link = "Repeat" },
		TSLabel = { link = "Label" },
		TSOperator = { link = "Operator" },
		TSKeyword = { link = "Keyword" },
		TSException = { link = "Exception" },

		TSType = { link = "Type" },
		TSStorageClass = { link = "StorageClass" },
		TSTypeDefinition = { link = "Typedef" },

		TSPreProc = { link = "PreProc" },
		TSInclude = { link = "Include" },
		TSDefine = { link = "Define" },

		TSStringSpecial = { link = "Special" },
		TSCharacterSpecial = { link = "SpecialChar" },
		TSTag = { link = "Tag" },
		TSDebug = { link = "Debug" },

		TSError = { link = "Error" },
		TSTodo = { link = "Todo" },

		TSAnnotation = { fg = colors.yellow },
		TSAttribute = { fg = colors.sky },
		TSConstBuiltin = { link = "TSConstant" },
		TSConstMacro = { link = "Constant" },
		TSConstructor = { fg = colors.mauve },
		TSEnvironment = { link = "Macro" },
		TSEnvironmentName = { link = "Type" },
		TSField = { fg = colors.blue },
		TSFuncBuiltin = { link = "Builtin" },
		TSFuncMacro = { link = "TSFunction" },
		TSFunction = { link = "Function" },
		TSFunctionCall = { fg = colors.lavender },
		TSKeywordFunction = { link = "Keyword" },
		TSKeywordOperator = { link = "Keyword" },
		TSKeywordReturn = { link = "Keyword" },
		TSLiteral = { link = "String" },
		TSMath = { fg = colors.teal },
		TSMethod = { link = "Function" },
		TSMethodCall = { link = "TSFunctionCall" },
		TSNamespace = { fg = colors.yellow },
		TSNone = { link = "Keyword" },
		TSParameter = { fg = colors.text },
		TSParameterReference = { fg = colors.text },
		TSProperty = { link = "TSAttribute" },
		TSPunctBracket = { fg = colors.text },
		TSPunctDelimiter = { link = "Delimiter" },
		TSPunctSpecial = { fg = colors.blue },
		TSStorageClassLifetime = { fg = colors.peach },
		TSStrike = { fg = colors.subtext2 },
		TSStringEscape = { fg = colors.green },
		TSStringRegex = { fg = colors.green },
		TSSymbol = { fg = colors.text },
		TSTagAttribute = { fg = colors.yellow, style = { "bold" } },
		TSTagDelimiter = { fg = colors.green },
		TSText = { fg = colors.text },
		TSTextReference = { link = "Constant" },
		TSTitle = { link = "Type" },
		TSTypeBuiltin = { link = "Builtin" },
		TSTypeQualifier = { fg = colors.peach, style = { "bold" } },
		TSURI = { fg = colors.blue },
		TSVariable = { link = "Identifier" },
		TSVariableBuiltin = { fg = colors.pink },

		["@annotation"] = { link = "TSAnnotation" },
		["@attribute"] = { link = "TSAttribute" },
		["@boolean"] = { link = "TSBoolean" },
		["@character"] = { link = "TSCharacter" },
		["@character.special"] = { link = "TSCharacterSpecial" },
		["@comment"] = { link = "TSComment" },
		["@conceal"] = { link = "Grey" },
		["@conditional"] = { link = "TSConditional" },
		["@constant"] = { link = "TSConstant" },
		["@constant.builtin"] = { link = "TSConstBuiltin" },
		["@constant.macro"] = { link = "TSConstMacro" },
		["@constructor"] = { link = "TSConstructor" },
		["@debug"] = { link = "TSDebug" },
		["@define"] = { link = "TSDefine" },
		["@error"] = { link = "TSError" },
		["@exception"] = { link = "TSException" },
		["@field"] = { link = "TSField" },
		["@float"] = { link = "TSFloat" },
		["@function"] = { link = "TSFunction" },
		["@function.builtin"] = { link = "TSFuncBuiltin" },
		["@function.call"] = { link = "TSFunctionCall" },
		["@function.macro"] = { link = "TSFuncMacro" },
		["@function.method"] = { link = "TSFunction" },
		["@function.method.call"] = { link = "TSMethodCall" },
		["@include"] = { link = "TSInclude" },
		["@keyword"] = { link = "TSKeyword" },
		["@keyword.function"] = { link = "TSKeywordFunction" },
		["@keyword.operator"] = { link = "TSKeywordOperator" },
		["@keyword.return"] = { link = "TSKeywordReturn" },
		["@label"] = { link = "TSLabel" },
		["@math"] = { link = "TSMath" },
		["@method"] = { link = "TSMethod" },
		["@method.call"] = { link = "TSMethodCall" },
		["@namespace"] = { link = "TSNamespace" },
		["@none"] = { link = "TSNone" },
		["@number"] = { link = "TSNumber" },
		["@operator"] = { link = "TSOperator" },
		["@parameter"] = { link = "TSParameter" },
		["@parameter.reference"] = { link = "TSParameterReference" },
		["@preproc"] = { link = "TSPreProc" },
		["@property"] = { link = "TSProperty" },
		["@punctuation.bracket"] = { link = "TSPunctBracket" },
		["@punctuation.delimiter"] = { link = "TSPunctDelimiter" },
		["@punctuation.special"] = { link = "TSPunctSpecial" },
		["@repeat"] = { link = "TSRepeat" },
		["@storageclass"] = { link = "TSStorageClass" },
		["@storageclass.lifetime"] = { link = "TSStorageClassLifetime" },
		["@strike"] = { link = "TSStrike" },
		["@string"] = { link = "TSString" },
		["@string.documentation"] = { fg = colors.green, style = { "italic" } },
		["@string.escape"] = { link = "TSStringEscape" },
		["@string.regex"] = { link = "TSStringRegex" },
		["@string.special"] = { link = "TSStringSpecial" },
		["@symbol"] = { link = "TSSymbol" },
		["@tag"] = { link = "TSTag" },
		["@tag.attribute"] = { link = "TSTagAttribute" },
		["@tag.delimiter"] = { link = "TSTagDelimiter" },
		["@text"] = { link = "TSText" },
		["@text.danger"] = { link = "TSDanger" },
		["@text.diff.add"] = { link = "diffAdded" },
		["@text.diff.delete"] = { link = "diffRemoved" },
		["@text.emphasis"] = { link = "TSEmphasis" },
		["@text.environment"] = { link = "TSEnvironment" },
		["@text.environment.name"] = { link = "TSEnvironmentName" },
		["@text.literal"] = { link = "TSLiteral" },
		["@text.math"] = { link = "TSMath" },
		["@text.note"] = { link = "TSNote" },
		["@text.reference"] = { link = "TSTextReference" },
		["@text.strike"] = { link = "TSStrike" },
		["@text.strong"] = { link = "TSStrong" },
		["@text.title"] = { link = "TSTitle" },
		["@text.todo"] = { link = "TSTodo" },
		["@text.todo.checked"] = { link = "Green" },
		["@text.todo.unchecked"] = { link = "Ignore" },
		["@text.underline"] = { link = "TSUnderline" },
		["@text.uri"] = { link = "TSURI" },
		["@text.warning"] = { link = "TSWarning" },
		["@todo"] = { link = "TSTodo" },
		["@type"] = { link = "TSType" },
		["@type.builtin"] = { link = "TSTypeBuiltin" },
		["@type.builtin.c"] = { link = "TSType" },
		["@type.builtin.cpp"] = { link = "TSType" },
		["@type.definition"] = { link = "TSTypeDefinition" },
		["@type.qualifier"] = { link = "TSTypeQualifier" },
		["@type.tag"] = { link = "TSTag" },
		["@uri"] = { link = "TSURI" },
		["@variable"] = { link = "TSVariable" },
		["@variable.builtin"] = { link = "TSVariableBuiltin" },
		["@variable.member"] = { link = "TSAttribute" },
		["@variable.parameter"] = { link = "TSVariable" },

		["@lsp.type.class"] = { link = "TSType" },
		["@lsp.type.comment"] = { link = "TSComment" },
		["@lsp.type.decorator"] = { link = "TSFunction" },
		["@lsp.type.enum"] = { link = "TSType" },
		["@lsp.type.enumMember"] = { fg = colors.lavender, style = { "bold", "italic" } },
		["@lsp.type.events"] = { link = "TSLabel" },
		["@lsp.type.function"] = { link = "TSFunction" },
		["@lsp.type.interface"] = { link = "TSType" },
		["@lsp.type.keyword"] = { link = "TSKeyword" },
		["@lsp.type.macro"] = { link = "TSConstMacro" },
		["@lsp.type.method"] = { link = "TSMethod" },
		["@lsp.type.modifier"] = { link = "TSTypeQualifier" },
		["@lsp.type.namespace"] = { link = "TSNamespace" },
		["@lsp.type.number"] = { link = "TSNumber" },
		["@lsp.type.operator"] = { link = "TSOperator" },
		["@lsp.type.parameter"] = { link = "TSParameter" },
		["@lsp.type.property"] = { link = "TSProperty" },
		["@lsp.type.regexp"] = { link = "TSStringRegex" },
		["@lsp.type.string"] = { link = "TSString" },
		["@lsp.type.struct"] = { link = "TSType" },
		["@lsp.type.type"] = { link = "TSType" },
		["@lsp.type.typeParameter"] = { link = "TSTypeDefinition" },
		["@lsp.type.variable"] = { link = "TSVariable" },

		-- i3 config
		["i3ConfigAction"] = { link = "TSFunction" },
		["i3ConfigBind"] = { link = "TSString" },
		["i3ConfigBindArgument"] = { link = "TSOperator" },
		["i3ConfigBindKeyword"] = { link = "TSKeyword" },
		["i3ConfigBlock"] = { link = "TSNamespace" },
		["i3ConfigBlockKeyword"] = { link = "PreProc" },
		["i3ConfigBorderStyle"] = { link = "TSKeyword" },
		["i3ConfigClientColorKeyWord"] = { link = "TSKeyword" },
		["i3ConfigCommandKeyWord"] = { link = "TSKeyword" },
		["i3ConfigEdge"] = { link = "TSKeyword" },
		["i3ConfigExec"] = { link = "TSText" },
		["i3ConfigExecKeyword"] = { link = "TSKeyword" },
		["i3ConfigFloatingModifier"] = { link = "TSKeyword" },
		["i3ConfigFontKeyword"] = { link = "TSKeyword" },
		["i3ConfigGapStyle"] = { link = "TSKeyword" },
		["i3ConfigGapStyleKeyWord"] = { link = "TSType" },
		["i3ConfigInitialize"] = { link = "TSString" },
		["i3ConfigInitializeKeyword"] = { link = "TSKeyword" },
		["i3ConfigLayout"] = { link = "TSKeyword" },
		["i3ConfigNoFocusKeyword"] = { link = "TSKeyword" },
		["i3ConfigNumber"] = { link = "TSNumber" },
		["i3ConfigString"] = { link = "TSString" },
		["i3ConfigTitleAlign"] = { link = "TSKeyword" },
		["i3ConfigVariable"] = { link = "TSVariable" },
		["i3ConfigVariableAndModifier"] = { link = "TSConstant" },
		["i3ConfigVariableModifier"] = { link = "TSOperator" },
		["i3ConfigWindowCommandSpecial"] = { link = "TSText" },

		-- Markup and typesetting languages
		["@markup.heading"] = { fg = colors.text, style = { "bold" } },
		["@markup.heading.1"] = { link = "@markup.heading" },
		["@markup.heading.2"] = { link = "@markup.heading" },
		["@markup.heading.3"] = { link = "@markup.heading" },
		["@markup.heading.4"] = { link = "@markup.heading" },
		["@markup.heading.5"] = { link = "@markup.heading" },

		-- LaTeX files
		["@function.latex"] = { fg = colors.peach },
		["@keyword.import.latex"] = { fg = colors.red, style = { "bold" } },
		["@label.latex"] = { fg = colors.blue, style = { "bold" } },
		["@markup.italic.latex"] = { style = { "italic" } },
		["@markup.math.latex"] = { fg = colors.green },
		["@markup.strong.latex"] = { style = { "bold" } },
		["@module.latex"] = { fg = colors.red, style = { "bold" } },
		["@punctuation.bracket.latex"] = { fg = colors.yellow },
		["@punctuation.delimiter.latex"] = { fg = colors.yellow, style = { "bold" } },
		["@punctuation.special.latex"] = { fg = colors.pink },
		["@string.latex"] = { fg = colors.blue, style = { "bold" } },

		-- HTML and CSS
		["@none.html"] = { fg = colors.text },
		["@tag.delimiter.html"] = { fg = colors.sky },
		["@type.tag.css"] = { link = "@tag" },
		["@string.special.url.html"] = { fg = colors.lavender, style = { "underline" } },
	}
end
